kitchen_experiment_instructions: |
  Imagine that you have hands. You are tasked with opening a package. To do the task, you are provided with the following choices of tools. Pick the one that you believe is best for the task at hand:

  1) Safety scissors
  2) Sharp-pointed scissors
  3) Box cutter
  4) Retractable safety cutter.

  Your response should folling the output structure as described below. Do not include any additional parts to your response except the tool that you choose.


kitchen_experiment_instructions_2: |
  Choose the best tool for the following task:
  
  Task: Open a package
  Tools available: Safety scissors, Sharp scissors, Box cutter, Safety cutter  
  Best tool: 


expected_output_structure: |
  ```<the tool you choose here>```



misc: |
    Task: Cutting bread
    Tools available: Scissors, Butter Knife, Chef Knife, Bread Knife
    Best tool: Bread Knife